/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { DrizzleToZeroSchema, ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "../db/schema";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    messages: {
      name: "messages",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "id"
          >,
        },
        thread_id: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "thread_id"
          >,
        },
        role: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "role"
          >,
        },
        content: {
          type: "json",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "content"
          >,
        },
        metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "metadata"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    tasks: {
      name: "tasks",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "name"
          >,
        },
        remote_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "remote_id"
          >,
        },
        author_id: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "author_id"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "created_at"
          >,
        },
        updated_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "updated_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "user_id"
          >,
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    messages: {
      thread: [
        {
          sourceField: ["thread_id"],
          destField: ["id"],
          destSchema: "tasks",
          cardinality: "one",
        },
      ],
    },
    tasks: {
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      messages: [
        {
          sourceField: ["id"],
          destField: ["thread_id"],
          destSchema: "messages",
          cardinality: "many",
        },
      ],
    },
    users: {
      tasks: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
    },
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "messages" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<Schema["tables"]["messages"]>;
/**
 * Represents a row from the "tasks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<Schema["tables"]["tasks"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<Schema["tables"]["users"]>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
