/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { DrizzleToZeroSchema, ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "../db/schema";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    agents: {
      name: "agents",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "name"
          >,
        },
        system_prompt: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "system_prompt"
          >,
        },
        base_agent: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "base_agent"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "created_at"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "organisation_id"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "author_id"
          >,
        },
      },
      primaryKey: ["id"],
    },
    messages: {
      name: "messages",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "id"
          >,
        },
        task_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "task_id"
          >,
        },
        message_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "message_id"
          >,
        },
        role: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "role"
          >,
        },
        content: {
          type: "json",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "content"
          >,
        },
        metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "metadata"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    organisations: {
      name: "organisations",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organisations",
            "id"
          >,
        },
      },
      primaryKey: ["id"],
    },
    projects: {
      name: "projects",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "name"
          >,
        },
        path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "path"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "created_at"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "organisation_id"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "author_id"
          >,
        },
      },
      primaryKey: ["id"],
    },
    tasks: {
      name: "tasks",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "name"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "organisation_id"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "author_id"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "created_at"
          >,
        },
        agent_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "agent_id"
          >,
        },
        project_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "project_id"
          >,
        },
        updated_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "updated_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "id"
          >,
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    agents: {
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["agent_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
    },
    messages: {
      task: [
        {
          sourceField: ["task_id"],
          destField: ["id"],
          destSchema: "tasks",
          cardinality: "one",
        },
      ],
    },
    organisations: {
      agents: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "agents",
          cardinality: "many",
        },
      ],
      projects: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "projects",
          cardinality: "many",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
    },
    projects: {
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["project_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
    },
    tasks: {
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      agent: [
        {
          sourceField: ["agent_id"],
          destField: ["id"],
          destSchema: "agents",
          cardinality: "one",
        },
      ],
      project: [
        {
          sourceField: ["project_id"],
          destField: ["id"],
          destSchema: "projects",
          cardinality: "one",
        },
      ],
      messages: [
        {
          sourceField: ["id"],
          destField: ["task_id"],
          destSchema: "messages",
          cardinality: "many",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
    },
    users: {
      tasks: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
      agents: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "agents",
          cardinality: "many",
        },
      ],
      projects: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "projects",
          cardinality: "many",
        },
      ],
    },
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "agents" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Agent = Row<Schema["tables"]["agents"]>;
/**
 * Represents a row from the "messages" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<Schema["tables"]["messages"]>;
/**
 * Represents a row from the "organisations" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Organisation = Row<Schema["tables"]["organisations"]>;
/**
 * Represents a row from the "projects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<Schema["tables"]["projects"]>;
/**
 * Represents a row from the "tasks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<Schema["tables"]["tasks"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<Schema["tables"]["users"]>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
