/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { DrizzleToZeroSchema, ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "../db/schema";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    agents: {
      name: "agents",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "name"
          >,
        },
        system_prompt: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "system_prompt"
          >,
        },
        base_agent: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "base_agent"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "created_at"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "organisation_id"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "agents",
            "author_id"
          >,
        },
      },
      primaryKey: ["id"],
    },
    mcpStore: {
      name: "mcpStore",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "id"
          >,
        },
        slug: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "slug"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "name"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "description"
          >,
        },
        logo_url: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "logo_url"
          >,
        },
        category: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "category"
          >,
        },
        mcp_server_url: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "mcp_server_url"
          >,
        },
        default_scopes: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "default_scopes"
          >,
        },
        is_active: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "is_active"
          >,
        },
        sort_order: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "sort_order"
          >,
        },
        metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "metadata"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "created_at"
          >,
        },
        updated_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcpStore",
            "updated_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "mcp_store",
    },
    mcps: {
      name: "mcps",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "id"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "organisation_id"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "author_id"
          >,
        },
        mcp_store_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "mcp_store_id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "name"
          >,
        },
        custom_mcp_url: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "custom_mcp_url"
          >,
        },
        custom_description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "custom_description"
          >,
        },
        mcp_server_url: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "mcp_server_url"
          >,
        },
        oauth_client_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "oauth_client_id"
          >,
        },
        oauth_client_secret: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "oauth_client_secret"
          >,
        },
        oauth_metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "oauth_metadata"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "created_at"
          >,
        },
        updated_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "mcps",
            "updated_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    messages: {
      name: "messages",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "id"
          >,
        },
        task_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "task_id"
          >,
        },
        message_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "message_id"
          >,
        },
        role: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "role"
          >,
        },
        content: {
          type: "json",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "content"
          >,
        },
        metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "metadata"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messages",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    oauthConnections: {
      name: "oauthConnections",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "user_id"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "organisation_id"
          >,
        },
        mcp_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "mcp_id"
          >,
        },
        access_token: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "access_token"
          >,
        },
        refresh_token: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "refresh_token"
          >,
        },
        token_type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "token_type"
          >,
        },
        expires_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "expires_at"
          >,
        },
        scope: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "scope"
          >,
        },
        provider_user_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "provider_user_id"
          >,
        },
        provider_metadata: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "provider_metadata"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "created_at"
          >,
        },
        updated_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthConnections",
            "updated_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "oauth_connections",
    },
    oauthStates: {
      name: "oauthStates",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "id"
          >,
        },
        state: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "state"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "user_id"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "organisation_id"
          >,
        },
        mcp_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "mcp_id"
          >,
        },
        redirect_uri: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "redirect_uri"
          >,
        },
        code_verifier: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "code_verifier"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "created_at"
          >,
        },
        expires_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "oauthStates",
            "expires_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "oauth_states",
    },
    organisations: {
      name: "organisations",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organisations",
            "id"
          >,
        },
        payment_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organisations",
            "payment_id"
          >,
        },
        wallet: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organisations",
            "wallet"
          >,
        },
      },
      primaryKey: ["id"],
    },
    projects: {
      name: "projects",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "name"
          >,
        },
        path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "path"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "created_at"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "organisation_id"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "projects",
            "author_id"
          >,
        },
      },
      primaryKey: ["id"],
    },
    tasks: {
      name: "tasks",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "name"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "organisation_id"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "author_id"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "created_at"
          >,
        },
        agent_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "agent_id"
          >,
        },
        project_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "project_id"
          >,
        },
        updated_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "tasks",
            "updated_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    usage: {
      name: "usage",
      columns: {
        id: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "id"
          >,
        },
        organisation_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "organisation_id"
          >,
        },
        model: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "model"
          >,
        },
        input_tokens: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "input_tokens"
          >,
        },
        output_tokens: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "output_tokens"
          >,
        },
        cache_creation_input_tokens: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "cache_creation_input_tokens"
          >,
        },
        cache_read_input_tokens: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "cache_read_input_tokens"
          >,
        },
        cost: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "cost"
          >,
        },
        created_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usage",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "id"
          >,
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    agents: {
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["agent_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
    },
    mcpStore: {
      mcps: [
        {
          sourceField: ["id"],
          destField: ["mcp_store_id"],
          destSchema: "mcps",
          cardinality: "many",
        },
      ],
    },
    mcps: {
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      mcpStore: [
        {
          sourceField: ["mcp_store_id"],
          destField: ["id"],
          destSchema: "mcpStore",
          cardinality: "one",
        },
      ],
      oauthConnections: [
        {
          sourceField: ["id"],
          destField: ["mcp_id"],
          destSchema: "oauthConnections",
          cardinality: "many",
        },
      ],
      oauthStates: [
        {
          sourceField: ["id"],
          destField: ["mcp_id"],
          destSchema: "oauthStates",
          cardinality: "many",
        },
      ],
    },
    messages: {
      task: [
        {
          sourceField: ["task_id"],
          destField: ["id"],
          destSchema: "tasks",
          cardinality: "one",
        },
      ],
    },
    oauthConnections: {
      user: [
        {
          sourceField: ["user_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
      mcp: [
        {
          sourceField: ["mcp_id"],
          destField: ["id"],
          destSchema: "mcps",
          cardinality: "one",
        },
      ],
    },
    oauthStates: {
      user: [
        {
          sourceField: ["user_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
      mcp: [
        {
          sourceField: ["mcp_id"],
          destField: ["id"],
          destSchema: "mcps",
          cardinality: "one",
        },
      ],
    },
    organisations: {
      agents: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "agents",
          cardinality: "many",
        },
      ],
      projects: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "projects",
          cardinality: "many",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
      usage: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "usage",
          cardinality: "many",
        },
      ],
      mcps: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "mcps",
          cardinality: "many",
        },
      ],
      oauthConnections: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "oauthConnections",
          cardinality: "many",
        },
      ],
      oauthStates: [
        {
          sourceField: ["id"],
          destField: ["organisation_id"],
          destSchema: "oauthStates",
          cardinality: "many",
        },
      ],
    },
    projects: {
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["project_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
    },
    tasks: {
      user: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      agent: [
        {
          sourceField: ["agent_id"],
          destField: ["id"],
          destSchema: "agents",
          cardinality: "one",
        },
      ],
      project: [
        {
          sourceField: ["project_id"],
          destField: ["id"],
          destSchema: "projects",
          cardinality: "one",
        },
      ],
      messages: [
        {
          sourceField: ["id"],
          destField: ["task_id"],
          destSchema: "messages",
          cardinality: "many",
        },
      ],
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
    },
    usage: {
      organisation: [
        {
          sourceField: ["organisation_id"],
          destField: ["id"],
          destSchema: "organisations",
          cardinality: "one",
        },
      ],
    },
    users: {
      tasks: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "tasks",
          cardinality: "many",
        },
      ],
      agents: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "agents",
          cardinality: "many",
        },
      ],
      projects: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "projects",
          cardinality: "many",
        },
      ],
      mcps: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "mcps",
          cardinality: "many",
        },
      ],
      oauthConnections: [
        {
          sourceField: ["id"],
          destField: ["user_id"],
          destSchema: "oauthConnections",
          cardinality: "many",
        },
      ],
      oauthStates: [
        {
          sourceField: ["id"],
          destField: ["user_id"],
          destSchema: "oauthStates",
          cardinality: "many",
        },
      ],
    },
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "agents" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Agent = Row<Schema["tables"]["agents"]>;
/**
 * Represents a row from the "mcpStore" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type McpStore = Row<Schema["tables"]["mcpStore"]>;
/**
 * Represents a row from the "mcps" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Mcp = Row<Schema["tables"]["mcps"]>;
/**
 * Represents a row from the "messages" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<Schema["tables"]["messages"]>;
/**
 * Represents a row from the "oauthConnections" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type OauthConnection = Row<Schema["tables"]["oauthConnections"]>;
/**
 * Represents a row from the "oauthStates" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type OauthState = Row<Schema["tables"]["oauthStates"]>;
/**
 * Represents a row from the "organisations" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Organisation = Row<Schema["tables"]["organisations"]>;
/**
 * Represents a row from the "projects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<Schema["tables"]["projects"]>;
/**
 * Represents a row from the "tasks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<Schema["tables"]["tasks"]>;
/**
 * Represents a row from the "usage" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Usage = Row<Schema["tables"]["usage"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<Schema["tables"]["users"]>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
