/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthoriseRouteImport } from './routes/authorise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SettingsWalletRouteImport } from './routes/settings/wallet'
import { Route as SettingsClaudeCodeRouteImport } from './routes/settings/claude-code'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoriseRoute = AuthoriseRouteImport.update({
  id: '/authorise',
  path: '/authorise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWalletRoute = SettingsWalletRouteImport.update({
  id: '/settings/wallet',
  path: '/settings/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsClaudeCodeRoute = SettingsClaudeCodeRouteImport.update({
  id: '/settings/claude-code',
  path: '/settings/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorise': typeof AuthoriseRoute
  '/home': typeof HomeRoute
  '/tasks': typeof TasksRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/wallet': typeof SettingsWalletRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorise': typeof AuthoriseRoute
  '/home': typeof HomeRoute
  '/tasks': typeof TasksRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/wallet': typeof SettingsWalletRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorise': typeof AuthoriseRoute
  '/home': typeof HomeRoute
  '/tasks': typeof TasksRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/claude-code': typeof SettingsClaudeCodeRoute
  '/settings/wallet': typeof SettingsWalletRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorise'
    | '/home'
    | '/tasks'
    | '/settings/appearance'
    | '/settings/claude-code'
    | '/settings/wallet'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorise'
    | '/home'
    | '/tasks'
    | '/settings/appearance'
    | '/settings/claude-code'
    | '/settings/wallet'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/authorise'
    | '/home'
    | '/tasks'
    | '/settings/appearance'
    | '/settings/claude-code'
    | '/settings/wallet'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthoriseRoute: typeof AuthoriseRoute
  HomeRoute: typeof HomeRoute
  TasksRoute: typeof TasksRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsClaudeCodeRoute: typeof SettingsClaudeCodeRoute
  SettingsWalletRoute: typeof SettingsWalletRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorise': {
      id: '/authorise'
      path: '/authorise'
      fullPath: '/authorise'
      preLoaderRoute: typeof AuthoriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/wallet': {
      id: '/settings/wallet'
      path: '/settings/wallet'
      fullPath: '/settings/wallet'
      preLoaderRoute: typeof SettingsWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/claude-code': {
      id: '/settings/claude-code'
      path: '/settings/claude-code'
      fullPath: '/settings/claude-code'
      preLoaderRoute: typeof SettingsClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthoriseRoute: AuthoriseRoute,
  HomeRoute: HomeRoute,
  TasksRoute: TasksRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsClaudeCodeRoute: SettingsClaudeCodeRoute,
  SettingsWalletRoute: SettingsWalletRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
